# Generated by Django 3.0.7 on 2020-07-15 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ToDoDashboard', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, upload_to='photos/')),
                ('department', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('label', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField(null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('time_estimate_hours', models.PositiveIntegerField(null=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoDashboard.DashboardColumn')),
                ('subtask_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToDoDashboard.ToDoItem')),
            ],
            options={
                'verbose_name': 'ToDo Item',
                'verbose_name_plural': 'ToDo Items',
                'ordering': ('updated_at',),
            },
        ),
        migrations.AddField(
            model_name='dashboardcolumn',
            name='dashboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToDoDashboard.Dashboard'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='ToDoDashboard.Member'),
        ),
    ]
